### ISSUE TITLE
 Two bugs

### ISSUE THREAD

**Issue by lifehaschanged** [iiz00/obsidian-multiple-notes-outline#26]
hello iizoo :) ,

thanks for this amazin plugin, it's a great tool for writing.

I have recently found two bugs in the console:

One thing I don't know what it's causing (SRY) but the other bug is a blank mno folder sidebar:

<img width="367" alt="2024-04-26 19_21_01-fsdfsdf - Bildungsvault - Obsidian v1 5 12" src="https://github.com/iiz00/obsidian-multiple-notes-outline/assets/81463128/be704602-f162-4ca5-87a8-6d42871500b4">
<img width="365" alt="2024-04-26 19_21_58-fsdfsdf - Bildungsvault - Obsidian v1 5 12" src="https://github.com/iiz00/obsidian-multiple-notes-outline/assets/81463128/a5ccc279-d6d3-409c-8982-7af4b4999c5f">

Edit: Sorry for the wrong FR. I changed the title of this issue, it's working with this plugin:
https://github.com/Raphlette/obsidian-new-tab-plus

**Comment by iiz00** [comment]
Thank you for using the plugin and reporting the issues!

Regarding the first error, I am currently investigating it. It likely does not impact the functionality, but I will look into it further.

As for the second error, I have attempted to fix the suspected cause in ~~v0.6.1~~v0.6.2. The issue was occurring when sorting items chronologically in Folder View if there were two or more subfolders present. Please test the new version and let me know if the problem persists.

**Comment by lifehaschanged** [comment]
It's working fine now! Thank you! The first error is not happening again (if it does I can reopen this issue) and opening many folders with subfolders is working properly!
